# Generated by Django 4.2.3 on 2023-07-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='isCommitted',
            field=models.BooleanField(default=False),
        ),
    ]
